app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\TransactionController;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// DATABASE MANAGEMENT ROUTES
Route::resource ( 'user', 'UserController', ['except' => []]);
//Route::get('user/{id}/img', 'UserController@image');
Route::post('user/{id}/img', 'UploadController@uploadUserIMG');
Route::post('user/{id}/img/delete', 'UploadController@deleteUserIMG');
Route::post('ship/{shipId}/img', 'UploadController@uploadShipIMG');
Route::resource ( 'user.ship', 'ShipController', ['except' => ['edit', 'create']]);

Route::resource ( 'cashbook', 'CashbookController', ['except' => ['edit', 'delete']] );

Route::post('export/{year}', 'ExportController@exportPDF');

Route::resource ( 'transaction', 'TransactionController', ['except' => ['edit', 'delete']]);
Route::get( 'transaction/open', 'TransactionController@showopen');
Route::get( 'transaction/import', 'TransactionController@showimport');
Route::post( 'transaction/import', 'TransactionController@import');

Route::resource ( 'category', 'CategoryController', ['except' => []]);

Route::resource ( 'account', 'AccountController', ['except' => ['edit']]);
Route::resource ( 'account.balance', 'AccountBalanceController', ['only' => ['store', 'update']]);


// APPLICATION GLOBAL ROUTES
// Main routes
Route::get ( '/', 'DashboardController@show' );

Route::get ( 'home', 'DashboardController@show' );

// function getDashboard() {
// 	if (Gate::denies('manage')) {
// 		return redirect(url('auth/login'));
// 	}
// 	return ();
// }

// Authentication Routes...
Route::get  ( 'auth/login',  'Auth\AuthController@getLogin'  );
Route::post ( 'auth/login',  'Auth\AuthController@postLogin' );
Route::get  ( 'auth/logout', 'Auth\AuthController@getLogout' );
Route::get  ( 'auth/profile', 'Auth\ProfileController@edit' );
Route::post ( 'auth/profile', 'Auth\ProfileController@update' );

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{

    	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'transaction';
	
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
			'account_name',
			'category_id',
			'date',
			'debt_credit', 
			'amount', 
			'counter_account', 
			'counter_name', 
			'type', 
			'description', 
	];
	
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [ 
	];
	
	/**
	 * Get the account that owns the transction.
	 */
	public function account()
	{
		return $this->belongsTo('App\Account', 'account_name', 'name');
	}
	
	/**
	 * Get the category that owns the transction.
	 */
	public function category()
	{
		return $this->belongsTo('App\Category');
	}


	public function getAmountStringAttribute() {
		return number_format($this->amount, 2, ',', '');
	}

	public function getTypeiconAttribute($value) {
		switch($this->type) {
			case 'ba' : return '<i class="fa fa-calculator"></i>';
			case 'id' : return '<i class="fa fa-credit-card"></i>';
			case 'kh' : return '<i class="fa fa-money"></i>';
			default: return "<strong>".$this->type."</strong>";
		}
		
	}
	
	public function getTypetitleAttribute($value) {
		switch($this->type) {
			case 'ac' : return 'acceptgiro';
			case 'ba' : return 'betaalautomaat';
			case 'bg' : return 'bankgiro opdracht';
			case 'cb' : return 'crediteurenbetaling';
			case 'ck' : return 'Chipknip';
			case 'db' : return 'diverse boekingen';
			case 'ei' : return 'euro-incasso';
			case 'ga' : return 'geldautomaat Euro';
			case 'gb' : return 'geldautomaat VV';
			case 'id' : return 'iDEAL';
			case 'kh' : return 'kashandeling';
			case 'ma' : return 'machtiging';
			case 'nb' : return 'NotaBox';
			case 'sb' : return 'salaris betaling';
			case 'sp' : return 'spoedopdracht';
			case 'tb' : return 'eigen rekening';
			case 'tg' : return 'telegiro';
			case 'CR' : return 'tegoed';
			case 'D' : return 'tekort';
			default: return "ONBEKEND";
		}
		
	}	
}

resources/views/partials/balancetable.blade.php
	<table class="table table-striped table-hover">
		<thead>
			<th class="col-sm-1 col-lg-1">Datum</th>
			<th class="col-sm-1 col-lg-1">Bedrag</th>
		</thead>
		<tbody>
			@foreach ($balances as $item)
			<tr>
				<td class="table-text"><strong>{!! date_create_from_format('Y-m-d', $item->date)->format('d-m-Y') !!}</strong></td>
				<td class="table-text">
					<span class="label label-{{ ($item->debt_credit == 'C') ? 'success' : 'danger' }}"><i class="fa fa-eur"></i> {{ $item->amount }}</span>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>

resources/views/partials/transactiontable.blade.php
	<table class="table table-striped table-hover">
		<thead>
			<th class="col-sm-1 col-lg-1">Datum</th>
			<th class="col-sm-4 col-lg-4">Rekening/Categorie</th>
			<th class="col-sm-1 col-lg-1">Bedrag</th>
			<th class="col-sm-2 col-lg-3">Tegenrekening</th>
			<th class="col-sm-4 col-lg-3">Omschrijving</th>
		</thead>
		<tbody>
			@foreach ($transactions as $t)
			<tr>
				<td class="table-text"><strong>{!! date_create_from_format('Y-m-d', $t->date)->format('d-m \<\b\r\/\> Y') !!}</strong></td>
				<td class="table-text">
					{{ $t->account->description }}<br/>
					@if($editCategory)
					{!! Form::model($t, ['route' => ['transaction.update', $t->id], 'method' => 'put', 'class' => 'form-inline']) !!}
					{!! Form::select('category_id', [null=>'Nog niet gerubriceerd'] + $cats->toArray(), null, ['class' => 'form-control']) !!}
					{!! Form::button('<i class="fa fa-floppy-o"></i>', array('type' => 'submit', 'class' => ($t->category_id==null) ? 'btn btn-warning' : 'btn btn-default')) !!}
					{!! Form::close() !!}
					@else
						@if($t->category)
						<small>{{ $t->category->name }}</small>
						@else
						<small><em>(geen categorie)</em></small>
						@endif
					@endif
				</td>
				<td class="table-text">
					<span class="label label-{{ ($t->debt_credit == 'C') ? 'success' : 'danger' }}"><i class="fa fa-eur"></i> {{ $t->amountString }}</span></td>
				<td class="table-text">{{ $t->counter_name }}<br/>
										<small>{{ $t->counter_account }}&nbsp</small></td>
				<td class="table-text"><abbr title="{{ $t->typetitle }}">{!! $t->typeicon !!}</abbr> {{ $t->description }}</td>
			</tr>
			@endforeach
		</tbody>
	</table>