app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\TransactionController;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// DATABASE MANAGEMENT ROUTES
Route::resource ( 'user', 'UserController', ['except' => []]);
//Route::get('user/{id}/img', 'UserController@image');
Route::post('user/{id}/img', 'UploadController@uploadUserIMG');
Route::post('user/{id}/img/delete', 'UploadController@deleteUserIMG');
Route::post('ship/{shipId}/img', 'UploadController@uploadShipIMG');
Route::resource ( 'user.ship', 'ShipController', ['except' => ['edit', 'create']]);

Route::resource ( 'cashbook', 'CashbookController', ['except' => ['edit', 'delete']] );

Route::post('export/{year}', 'ExportController@exportPDF');

Route::resource ( 'transaction', 'TransactionController', ['except' => ['edit', 'delete']]);
Route::get( 'transaction/open', 'TransactionController@showopen');
Route::get( 'transaction/import', 'TransactionController@showimport');
Route::post( 'transaction/import', 'TransactionController@import');

Route::resource ( 'category', 'CategoryController', ['except' => []]);

Route::resource ( 'account', 'AccountController', ['except' => ['edit']]);
Route::resource ( 'account.balance', 'AccountBalanceController', ['only' => ['store', 'update']]);


// APPLICATION GLOBAL ROUTES
// Main routes
Route::get ( '/', 'DashboardController@show' );

Route::get ( 'home', 'DashboardController@show' );

// function getDashboard() {
// 	if (Gate::denies('manage')) {
// 		return redirect(url('auth/login'));
// 	}
// 	return ();
// }

// Authentication Routes...
Route::get  ( 'auth/login',  'Auth\AuthController@getLogin'  );
Route::post ( 'auth/login',  'Auth\AuthController@postLogin' );
Route::get  ( 'auth/logout', 'Auth\AuthController@getLogout' );
Route::get  ( 'auth/profile', 'Auth\ProfileController@edit' );
Route::post ( 'auth/profile', 'Auth\ProfileController@update' );

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Support\Facades\Hash;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'user';
	
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [ 
			'username',
			'password' 
	];
	
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [ 
			'password',
			'remember_token' 
	];
	
    /**
     * Get the student's full name.
     *
     * @param  string  $value
     * @return string
     */
    public function getNameFullAttribute($value)
    {
    	$result = $this->name_first . ' ';
    	if (strlen($this->name_middle)>0)
    		$result .= $this->name_middle . ' ';
    	$result .= $this->name_last;
        return $result;
    }
    
	Public function setPasswordAttribute($password)
	{
		return $this->attributes['password'] = Hash::make($password);
	}
	
	public function ships() {
		return $this->hasMany('App\Ship', 'owner_id'); 
	}

	public function getPrimairShipAttribute() {
		return $this->ships()->where('primair', 1)->first();
	}

}

resources/views/layouts/admin.blade.php
@extends('layouts.app')

@section('body')
<!-- include the content -->
<div class="row">
	<div class="col-sm-3 col-md-2 sidebar">
		<div class="nav nav-sidebar">
			<ul class="nav nav-pills nav-stacked">
				<li><a href="{!! url('/') !!}"><i class="fa fa-tachometer fa-2x fa-fw"></i>&nbspDashboard</a>
				<li class="nav-divider"></li>
				<li>
					<a class="nav-container" data-toggle="collapse" data-parent="#stacked-menu" href="#cb">
						<i class="fa fa-money fa-2x fa-fw"></i>&nbspKasboek<div class="caret-container"><span class="caret arrow"></span></div>
					</a>
					<ul class="nav nav-pills nav-stacked collapse" id="cb">
						<li><a href="{!! url('/') !!}">Overzicht</a></li>						
						<li><a href="{!! url('/') !!}">Invoeren kastransactie</a></li>						
						<li><a href="{!! url('/') !!}">Invoeren storting</a></li>						
					</ul>
				</li>
				<li>
					<a class="nav-container" data-toggle="collapse" data-parent="#stacked-menu" href="#la">
						<i class="fa fa-users fa-2x fa-fw"></i>&nbspLeden<div class="caret-container"><span class="caret arrow"></span></div>
					</a>
					<ul class="nav nav-pills nav-stacked collapse in" id="la">
						<li class="active"><a href="{!! url('user') !!}">Overzicht</a></li>						
						<li><a href="{!! url('/') !!}">Nieuw lid</a></li>						
					</ul>
				</li>
				<li>
					<a class="nav-container" data-toggle="collapse" data-parent="#stacked-menu" href="#ac">
						<i class="fa fa-eur fa-2x fa-fw"></i>&nbspFinanciën<div class="caret-container"><span class="caret arrow"></span></div>
					</a>
					<ul class="nav nav-pills nav-stacked collapse" id="ac">
						<li><a href="{!! url('user') !!}">Rekening Courant</a></li>						
						<li><a href="{!! url('user') !!}">Kas</a></li>						
						<li><a href="{!! url('/') !!}">Spaarrekening</a></li>						
					</ul>
				</li>
				<li>
					<a class="nav-container" data-toggle="collapse" data-parent="#stacked-menu" href="#sg">
						<i class="fa fa-life-ring fa-2x fa-fw"></i>&nbspStamgegevens<div class="caret-container"><span class="caret arrow"></span></div>
					</a>
					<ul class="nav nav-pills nav-stacked collapse" id="sg">
						<li><a href="{!! url('account') !!}">Rekeningen</a></li>						
						<li><a href="{!! url('category') !!}">Categoriën</a></li>						
					</ul>
				</li>
				{{-- show tools section if present --}}
				@if (array_key_exists('tools', View::getSections()))
	                <li class="nav-divider"></li>
					@yield('tools')
				@endif
			</ul>				
		</div>
	</div>
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	@if (array_key_exists('title', View::getSections()))
	<div class="page-header"><h1>@yield('title', 'title section here')</h1></div>
	@endif
		{{-- error section --}}
		@include('common.errors')
		@include('common.success')
	
		@yield('content')
				
	</div>
</div>
@endsection

resources/views/layouts/app.blade.php
@extends('layouts.master')

@section('ul-navbar-right')
@if ( Auth::check() )
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" 
		   role="button" aria-haspopup="true" aria-expanded="false">
		   	{{ Auth::user()->name_full }} <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="{{ url('auth/profile') }}"><i class="fa fa-user"></i>&nbspManage account</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="{{ url('auth/logout') }}"><i class="fa fa-power-off"></i>&nbspLog out</a></li>
			</ul>
	</li>
@else
	<li><a href="{{ url('auth/login') }}">Login</a></li>
@endif
@endsection

@section('body')
<!-- include the content -->
<div class="row">
	<div class="col-sm-3 col-md-2 sidebar">
		<div class="nav nav-sidebar">
			<ul class="nav nav-pills nav-stacked">
				@include('common.menu')
			</ul>
		</div>
	</div>
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	@if (array_key_exists('title', View::getSections()))
	<div class="page-header"><h1>@yield('title', 'title section here')</h1></div>
	@endif
		{{-- error section --}}
		@include('common.errors')
		@include('common.success')
	
		@yield('content')
				
	</div>
</div>
@endsection

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>DNHAdmin</title>
	<link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
	
	{!! Html::style('css/app.css') !!}
		
</head>

<body>
	<div class="container-fluid">
		<nav class="navbar navbar-inverse  navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand logo" href="{{ url('/') }}"><i class="fa fa-anchor"></i>&nbspDNHAdmin</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						@yield('ul-navbar-left')
					</ul>
					<ul class="nav navbar-nav navbar-right">
						@yield('ul-navbar-right')
					</ul>
				</div>
			</div>
		</nav>
		@yield('body')
	</div>
	@yield('modals')
	
	{!! Html::script('js/app.js') !!}
	<!-- include additional scripts -->
	@yield('scripts')
	</body>
</html>